name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    if: github.repository == 'asd55667/nextjs-template'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.12.0"

      - name: Create Version PR
        id: changesets
        uses: changesets/action@v1.4.9
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          version: node .github/changeset-version.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: "production"

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version < package.json)
          echo "VERSION=v${VERSION}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
